# FUNCIONES Y MÉTODOS ELEMENTALES CON NUMPY(ARRAYS)

En el siguiente método hay diferentes operaciones y métodos con arrays. 

In [3]:
# IMPORTAR NUMPY 

import numpy as np

In [4]:
# CREAR UNA LISTA CON LOS NÚMEROS PRIMOS 

numeros_primos = [1,2,3,5,7,11]

In [5]:
# CREAR UN ARRAY A PARTIR DE LA LISTA

array_primos = np.array(numeros_primos)
array_primos

array([ 1,  2,  3,  5,  7, 11])

In [6]:
# CREAR ARRAYS CON CEROS

array_zeros = np.zeros(10)
array_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
# ARRAY DE SOLO UNOS 

array_unos = np.ones(10)
array_unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
# CREAR ARRAYS CON NUMEROS SUCECIVOS 

array_numeros = np.arange(10)
array_numeros

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# ARRAY CON NUMEROS IMPARES 

arrays_impares=np.arange(1,20,2)
arrays_impares

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [10]:
# ARRAY DE NUMEROS PARES

arrays_pares=np.arange(0,20,2)
arrays_pares 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
# CONVERTIR DE UNA DIMENSIÓN A DOS DIMENSIONES 

arrays_pares.reshape(2,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [12]:
# SUMAR 1 A TODOS LOS ELEMENTOS DEL ARRAY DE PARES PARA QUE AHORA SEAN IMPARES

array_impares = arrays_pares + 1 
array_impares

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [13]:
# MULTIPLICACIÓN DE LOS ARRAYS POR 100

array_multiplicado = array_impares * 100
array_multiplicado

array([ 100,  300,  500,  700,  900, 1100, 1300, 1500, 1700, 1900])

In [14]:
# RESTA ENTREDOS ARRAYS

array_impares - arrays_pares

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [15]:
# SUMA DE TODOS LOS ELEMENTOS DEL ARRAY

array_primos.sum()

29

In [16]:
# PROMEDIO DE LOS OBJETOS DEL ARRAY 

array_primos.mean()

4.833333333333333

In [17]:
# VARIANZA DE LOS OBJETOS DEL ARRAY

array_primos.var()

11.472222222222223

In [18]:
# ORDENAR UN ARRAY

array_fibonacci = np.array([55,0,144,1,21,89,5,8,13,1,34,3,2,222])
fibonacci_ordenado = np.sort(array_fibonacci)
fibonacci_ordenado

array([  0,   1,   1,   2,   3,   5,   8,  13,  21,  34,  55,  89, 144,
       222])

In [19]:
# ORDEN DESENDENTE 

-np.sort(-array_fibonacci)

array([222, 144,  89,  55,  34,  21,  13,   8,   5,   3,   2,   1,   1,
         0])

In [20]:
# SELECCIONAR UN ALEMENTO

fibonacci_ordenado[8]

21

In [21]:
# SELECCIONAR VARIOS ELEMENTOS 

fibonacci_ordenado[4:8]

array([ 3,  5,  8, 13])

In [22]:
# SELECCIONAR EL PRIMER ELEMENTO DE UN ARRAY DE MÁS DE UNA DIMENSIÓN

fibonacci_dos_dimensiones = fibonacci_ordenado.reshape(2,7)
fibonacci_dos_dimensiones[0,0]

0

In [23]:
fibonacci_dos_dimensiones

array([[  0,   1,   1,   2,   3,   5,   8],
       [ 13,  21,  34,  55,  89, 144, 222]])

In [24]:
# SELECCIONAR EL PRIMER CUARTO ELEMENTO DE LA SEGUNDA FILA

fibonacci_dos_dimensiones[1,3]

55

In [25]:
# SELECCIONAR VARIOS ELEMENTOS

fibonacci_dos_dimensiones[0,2],fibonacci_dos_dimensiones[1,4]

(1, 89)

In [26]:
# SELECCIONAR TODA LA FILA

fibonacci_dos_dimensiones[1,:]

array([ 13,  21,  34,  55,  89, 144, 222])

In [27]:
# SELECCIONAR TODA LA COLUMNA 

fibonacci_dos_dimensiones[:,3]

array([ 2, 55])

In [28]:
array_fibonacci

array([ 55,   0, 144,   1,  21,  89,   5,   8,  13,   1,  34,   3,   2,
       222])

In [29]:
# MOSTRARLOS MENORES A 34 EN BOLEANO

array_fibonacci<34

array([False,  True, False,  True,  True, False,  True,  True,  True,
        True, False,  True,  True, False])

In [30]:
# MOSTRARLOS MENORES A 34

array_fibonacci[array_fibonacci < 34]

array([ 0,  1, 21,  5,  8, 13,  1,  3,  2])